import type { Cargo, Container, PlacedCargo } from '../types'

const EPS=0.5
type Progress=(percent:number)=>void
type Options={signal?:AbortSignal}
type Orientation={length:number;width:number;height:number;rotation:0|90}
type SupportKind='floor'|'cargo'
type FreeSpace={x:number;y:number;z:number;length:number;width:number;height:number;supported:boolean;supportKind:SupportKind;supportCargoId?:string;supportCargoType?:Cargo['type'];supportLoadBearing?:boolean}
type Group={cargo:Cargo;quantity:number}
type Batch={space:FreeSpace;orientation:Orientation;score:number;take:number;positions:Array<{x:number;y:number;z:number}>;used:{x:number;y:number;length:number;width:number;height:number};fullBlock:boolean}
const abort=(s?:AbortSignal)=>{if(s?.aborted)throw new DOMException('Packing cancelled','AbortError')}
const yieldBrowser=()=>new Promise<void>(r=>typeof window!=='undefined'&&window.requestAnimationFrame?window.requestAnimationFrame(()=>r()):setTimeout(r,0))
function orientations(c:Cargo):Orientation[]{const a:Orientation={length:c.length,width:c.width,height:c.height,rotation:0};if(!c.rotatable||Math.abs(c.length-c.width)<EPS)return[a];return[a,{length:c.width,width:c.length,height:c.height,rotation:90}]}
function maxLayers(c:Cargo,o:Orientation,h:number){if(h+EPS<o.height)return 0;let n=Math.floor((h+EPS)/o.height);if(!c.stackable||!c.loadBearing)n=Math.min(n,1);const m=Number.isFinite(c.maxStackLayers)?Math.floor(c.maxStackLayers):0;if(m>0)n=Math.min(n,m);const top=Number.isFinite(c.maxLoadOnTop)?c.maxLoadOnTop:0;if(c.stackable&&c.loadBearing&&top>0&&c.weight>0)n=Math.min(n,Math.floor(top/c.weight)+1);return Math.max(1,n)}
function fits(s:FreeSpace,o:Orientation){return s.supported&&o.length<=s.length+EPS&&o.width<=s.width+EPS&&o.height<=s.height+EPS}
function split(s:FreeSpace,u:{x:number;y:number;length:number;width:number;height:number},full:boolean,c:Cargo){const a:FreeSpace[]=[];const x2=s.x+s.length,y2=s.y+s.width,ux=u.x+u.length,uy=u.y+u.width;const push=(x:number,y:number,z:number,l:number,w:number,h:number,supported:boolean,extra?:Partial<FreeSpace>)=>{if(l>EPS&&w>EPS&&h>EPS)a.push({x,y,z,length:l,width:w,height:h,supported, supportKind:s.supportKind, supportCargoId:s.supportCargoId, supportCargoType:s.supportCargoType, supportLoadBearing:s.supportLoadBearing,...extra})};const floor=s.z<=EPS;push(s.x,s.y,s.z,u.x-s.x,s.width,s.height,floor);push(ux,s.y,s.z,x2-ux,s.width,s.height,floor);push(u.x,s.y,s.z,u.length,u.y-s.y,s.height,floor);push(u.x,uy,s.z,u.length,y2-uy,s.height,floor);
  // A new upper free-space exists only when the placed footprint is a
  // complete rectangular support AND the item itself can carry a load.
  // This prevents floating boxes and makes load-bearing pallets useful as
  // dedicated support platforms for cartons / wooden crates.
  if(full&&c.loadBearing)push(u.x,u.y,s.z+u.height,u.length,u.width,s.height-u.height,true,{supportKind:'cargo',supportCargoId:c.id,supportCargoType:c.type,supportLoadBearing:true});
  return a}
function prune(a:FreeSpace[]){const v=a.filter(s=>s.length>EPS&&s.width>EPS&&s.height>EPS);return v.filter((s,i)=>!v.some((q,j)=>i!==j&&q.x<=s.x+EPS&&q.y<=s.y+EPS&&q.z<=s.z+EPS&&q.x+q.length>=s.x+s.length-EPS&&q.y+q.width>=s.y+s.width-EPS&&q.z+q.height>=s.z+s.height-EPS))}
function score(s:FreeSpace,o:Orientation,c:Container,cargo:Cargo){const dx=s.x+s.length/2-c.length/2,dy=s.y+s.width/2-c.width/2;const waste=(s.length-o.length*Math.floor((s.length+EPS)/o.length))*s.width+(s.width-o.width*Math.floor((s.width+EPS)/o.width))*s.length;const hw=Math.max(0,s.height-o.height*Math.floor((s.height+EPS)/o.height));let support=0;
  // Prefer load-bearing pallets as the base for cartons / wooden crates.
  // Avoid stacking pallets on pallets unless there is no alternative.
  if(cargo.type!=='pallet'&&s.supportKind==='cargo'&&s.supportCargoType==='pallet'&&s.supportLoadBearing)support-=25000;
  if(cargo.type==='pallet'&&s.supportKind==='cargo'&&s.supportCargoType==='pallet')support+=18000;
  // For the same support class, keep lower levels preferred.
  return Math.hypot(dx,dy)*.35+waste*.08+hw*.03+s.z*.05+support}
function boxesOverlap(a:{x:number;y:number;z:number;length:number;width:number;height:number},b:{x:number;y:number;z:number;length:number;width:number;height:number}){return a.x<b.x+b.length-EPS&&a.x+a.length>b.x+EPS&&a.y<b.y+b.width-EPS&&a.y+a.width>b.y+EPS&&a.z<b.z+b.height-EPS&&a.z+a.height>b.z+EPS}
function candidateBatch(s:FreeSpace,o:Orientation,c:Cargo,remaining:number,H:number):Batch|null{const cols=Math.floor((s.length+EPS)/o.length),rows=Math.floor((s.width+EPS)/o.width),layers=maxLayers(c,o,Math.min(s.height,Math.max(0,H-s.z)));if(cols<=0||rows<=0||layers<=0)return null;const capacity=cols*rows*layers,take=Math.min(remaining,capacity),per=cols*rows,fullLayers=Math.floor(take/per),rem=take%per,usedLayers=fullLayers+(rem?1:0),usedRows=rem?Math.ceil(rem/cols):rows,usedL=cols*o.length,usedW=usedRows*o.width,usedH=usedLayers*o.height,ux=s.x+Math.max(0,(s.length-usedL)/2),uy=s.y+Math.max(0,(s.width-usedW)/2);const positions:Array<{x:number;y:number;z:number}>=[];for(let layer=0,made=0;layer<usedLayers&&made<take;layer++){const count=layer<fullLayers?per:rem,rws=layer<fullLayers?rows:usedRows;if(!count)continue;for(let row=0;row<rws&&made<take;row++){const n=Math.min(cols,count-row*cols);for(let col=0;col<n;col++){const x=ux+col*o.length,y=uy+row*o.width,z=s.z+layer*o.height;if(x<-EPS||y<-EPS||x+o.length>H*0+Infinity||y+o.width>Infinity||z<-EPS||z+o.height>H+EPS)return null;positions.push({x,y,z});made++}}}const fullBlock=rem===0||rem%cols===0;return{space:s,orientation:o,score:0,take,positions,used:{x:ux,y:uy,length:usedL,width:usedW,height:usedH},fullBlock}}
function choose(spaces:FreeSpace[],cargo:Cargo,c:Container,remaining:number,H:number,current:PlacedCargo[]):Batch|undefined{let best:Batch|undefined;for(const s of spaces)for(const o of orientations(cargo)){if(!fits(s,o))continue;const b=candidateBatch(s,o,cargo,remaining,H);if(!b)continue;const collides=b.positions.some(p=>current.some(q=>boxesOverlap({x:p.x,y:p.y,z:p.z,length:o.length,width:o.width,height:o.height},{x:q.x,y:q.y,z:q.z,length:q.length,width:q.width,height:q.height})));if(collides)continue;b.score=score(s,o,cargo===undefined?c:c,cargo);if(!best||b.score<best.score)best=b}return best}
function groups(cargo:Cargo[]):Group[]{const m=new Map<string,Group>();for(const c of cargo){const q=Math.max(0,Math.floor(c.quantity));if(!q||c.length<=0||c.width<=0||c.height<=0)continue;const k=`${c.id}|${c.length}|${c.width}|${c.height}|${c.weight}|${c.stackable}|${c.loadBearing}|${c.rotatable}|${c.maxStackLayers}|${c.maxLoadOnTop}|${c.breakablePallet}`;const g=m.get(k);if(g)g.quantity+=q;else m.set(k,{cargo:c,quantity:q})}return[...m.values()].sort((a,b)=>{const ap=a.cargo.type==='pallet'&&a.cargo.loadBearing?1:0,bp=b.cargo.type==='pallet'&&b.cargo.loadBearing?1:0;if(ap!==bp)return bp-ap;const aa=a.cargo.length*a.cargo.width,bb=b.cargo.length*b.cargo.width;return bb-aa||(b.cargo.length*b.cargo.width*b.cargo.height-aa*a.cargo.length*a.cargo.width*a.cargo.height)})}
function placed(c:Cargo,i:number,o:Orientation,x:number,y:number,z:number):PlacedCargo{return{id:`${c.id}-${i+1}`,cargoId:c.id,cargoType:c.type,x,y,z,length:c.length,width:c.width,height:o.height,weight:c.weight,color:c.color,rotation:o.rotation,placementMode:'automatic',locked:false}}
function center(items:PlacedCargo[],c:Container){if(!items.length)return items;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const p of items){const l=p.rotation===90?p.width:p.length,w=p.rotation===90?p.length:p.width;minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x+l);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y+w)}const sx=(c.length-(maxX-minX))/2-minX,sy=(c.width-(maxY-minY))/2-minY;return Number.isFinite(sx)&&Number.isFinite(sy)?items.map(p=>({...p,x:p.x+sx,y:p.y+sy})):items}
function validate(items:PlacedCargo[],c:Container){for(let i=0;i<items.length;i++){const a=items[i];if(a.x<-EPS||a.y<-EPS||a.z<-EPS||a.x+a.length>c.length+EPS||a.y+a.width>c.width+EPS||a.z+a.height>c.height+EPS)return false;for(let j=i+1;j<items.length;j++)if(boxesOverlap(a,items[j]))return false}return true}
export async function packLaff(cargo:Cargo[],container:Container,progress?:Progress,options:Options={}){const gs=groups(cargo),total=gs.reduce((n,g)=>n+g.quantity,0);if(!total){progress?.(100);return[]}const H=Math.max(0,container.height);let done=0,seq=0,result:PlacedCargo[]=[];let spaces:FreeSpace[]=[{x:0,y:0,z:0,length:container.length,width:container.width,height:H,supported:true,supportKind:'floor'}];for(const g of gs){abort(options.signal);let remaining=g.quantity;const c=g.cargo;while(remaining>0){abort(options.signal);const choice=choose(spaces,c,container,remaining,H,result);if(!choice)break;const s=choice.space,o=choice.orientation,used=choice.used;spaces=prune([...spaces.filter(x=>x!==s),...split(s,used,choice.fullBlock,c)]);for(const p of choice.positions){result.push(placed(c,seq++,o,p.x,p.y,p.z));done++;progress?.(Math.min(99,Math.round(done/total*100)));if((done&31)===0)await yieldBrowser()}remaining-=choice.take;await yieldBrowser()}}
  const centered=center(result,container);
  // Centering is a pure translation, but keep a final hard validation barrier.
  // Never return a visually plausible but physically invalid load plan.
  const safe=validate(centered,container)?centered:result.filter((p,i)=>{if(p.x<-EPS||p.y<-EPS||p.z<-EPS||p.x+p.length>container.length+EPS||p.y+p.width>container.width+EPS||p.z+p.height>H+EPS)return false;for(let j=0;j<i;j++)if(boxesOverlap(p,result[j]))return false;return true});progress?.(100);return safe}
