import type { Cargo, Container, PlacedCargo } from '../types'

const EPS=0.5
type Progress=(percent:number)=>void
type Options={signal?:AbortSignal}
type Orientation={length:number;width:number;height:number;rotation:0|90}
type FreeSpace={x:number;y:number;z:number;length:number;width:number;height:number;supported:boolean}
type Group={cargo:Cargo;quantity:number}
const abort=(s?:AbortSignal)=>{if(s?.aborted)throw new DOMException('Packing cancelled','AbortError')}
const yieldBrowser=()=>new Promise<void>(r=>typeof window!=='undefined'&&window.requestAnimationFrame?window.requestAnimationFrame(()=>r()):setTimeout(r,0))
function orientations(c:Cargo):Orientation[]{const a:Orientation={length:c.length,width:c.width,height:c.height,rotation:0};if(!c.rotatable||Math.abs(c.length-c.width)<EPS)return[a];return[a,{length:c.width,width:c.length,height:c.height,rotation:90}]}
function maxLayers(c:Cargo,o:Orientation,h:number){if(h+EPS<o.height)return 0;let n=Math.floor((h+EPS)/o.height);if(!c.stackable||!c.loadBearing)n=Math.min(n,1);const m=Number.isFinite(c.maxStackLayers)?Math.floor(c.maxStackLayers):0;if(m>0)n=Math.min(n,m);const top=Number.isFinite(c.maxLoadOnTop)?c.maxLoadOnTop:0;if(c.stackable&&c.loadBearing&&top>0&&c.weight>0)n=Math.min(n,Math.floor(top/c.weight)+1);return Math.max(1,n)}
function fits(s:FreeSpace,o:Orientation){return s.supported&&o.length<=s.length+EPS&&o.width<=s.width+EPS&&o.height<=s.height+EPS}
function split(s:FreeSpace,u:{x:number;y:number;length:number;width:number;height:number},full:boolean){const a:FreeSpace[]=[];const x2=s.x+s.length,y2=s.y+s.width,ux=u.x+u.length,uy=u.y+u.width;const push=(x:number,y:number,z:number,l:number,w:number,h:number,supported:boolean)=>{if(l>EPS&&w>EPS&&h>EPS)a.push({x,y,z,length:l,width:w,height:h,supported})};const floor=s.z<=EPS;push(s.x,s.y,s.z,u.x-s.x,s.width,s.height,floor);push(ux,s.y,s.z,x2-ux,s.width,s.height,floor);push(u.x,s.y,s.z,u.length,u.y-s.y,s.height,floor);push(u.x,uy,s.z,u.length,y2-uy,s.height,floor);if(full)push(u.x,u.y,s.z+u.height,u.length,u.width,s.height-u.height,true);return a}
function prune(a:FreeSpace[]){const v=a.filter(s=>s.length>EPS&&s.width>EPS&&s.height>EPS);return v.filter((s,i)=>!v.some((q,j)=>i!==j&&q.x<=s.x+EPS&&q.y<=s.y+EPS&&q.z<=s.z+EPS&&q.x+q.length>=s.x+s.length-EPS&&q.y+q.width>=s.y+s.width-EPS&&q.z+q.height>=s.z+s.height-EPS))}
function score(s:FreeSpace,o:Orientation,c:Container){const dx=s.x+s.length/2-c.length/2,dy=s.y+s.width/2-c.width/2;const waste=(s.length-o.length*Math.floor((s.length+EPS)/o.length))*s.width+(s.width-o.width*Math.floor((s.width+EPS)/o.width))*s.length;const hw=Math.max(0,s.height-o.height*Math.floor((s.height+EPS)/o.height));return Math.hypot(dx,dy)*.35+waste*.08+hw*.03+s.z*.05}
function choose(spaces:FreeSpace[],cargo:Cargo,c:Container){let best:{space:FreeSpace;orientation:Orientation;score:number}|undefined;for(const s of spaces)for(const o of orientations(cargo))if(fits(s,o)){const sc=score(s,o,c);if(!best||sc<best.score)best={space:s,orientation:o,score:sc}}return best}
function groups(cargo:Cargo[]):Group[]{const m=new Map<string,Group>();for(const c of cargo){const q=Math.max(0,Math.floor(c.quantity));if(!q||c.length<=0||c.width<=0||c.height<=0)continue;const k=`${c.length}|${c.width}|${c.height}|${c.weight}|${c.stackable}|${c.loadBearing}|${c.rotatable}|${c.maxStackLayers}|${c.maxLoadOnTop}|${c.breakablePallet}`;const g=m.get(k);if(g)g.quantity+=q;else m.set(k,{cargo:c,quantity:q})}return[...m.values()].sort((a,b)=>b.cargo.length*b.cargo.width-a.cargo.length*a.cargo.width||(b.cargo.length*b.cargo.width*b.cargo.height-a.cargo.length*a.cargo.width*a.cargo.height))}
function placed(c:Cargo,i:number,o:Orientation,x:number,y:number,z:number):PlacedCargo{return{id:`${c.id}-${i+1}`,cargoId:c.id,cargoType:c.type,x,y,z,length:c.length,width:c.width,height:o.height,weight:c.weight,color:c.color,rotation:o.rotation,placementMode:'automatic',locked:false}}
function center(items:PlacedCargo[],c:Container){if(!items.length)return items;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const p of items){const l=p.rotation===90?p.width:p.length,w=p.rotation===90?p.length:p.width;minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x+l);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y+w)}const sx=(c.length-(maxX-minX))/2-minX,sy=(c.width-(maxY-minY))/2-minY;return Number.isFinite(sx)&&Number.isFinite(sy)?items.map(p=>({...p,x:p.x+sx,y:p.y+sy})):items}
export async function packLaff(cargo:Cargo[],container:Container,progress?:Progress,options:Options={}){const gs=groups(cargo),total=gs.reduce((n,g)=>n+g.quantity,0);if(!total){progress?.(100);return[]}const H=Math.max(0,container.height);let done=0,seq=0,result:PlacedCargo[]=[];let spaces:FreeSpace[]=[{x:0,y:0,z:0,length:container.length,width:container.width,height:H,supported:true}];for(const g of gs){abort(options.signal);let remaining=g.quantity;const c=g.cargo;while(remaining>0){abort(options.signal);const choice=choose(spaces,c,container);if(!choice)break;const s=choice.space,o=choice.orientation;const cols=Math.floor((s.length+EPS)/o.length),rows=Math.floor((s.width+EPS)/o.width),layers=maxLayers(c,o,Math.min(s.height,Math.max(0,H-s.z)));if(cols<=0||rows<=0||layers<=0)break;const capacity=cols*rows*layers,take=Math.min(remaining,capacity),per=cols*rows,fullLayers=Math.floor(take/per),rem=take%per,usedLayers=fullLayers+(rem?1:0),usedRows=rem?Math.ceil(rem/cols):rows,usedL=cols*o.length,usedW=usedRows*o.width,usedH=usedLayers*o.height,ux=s.x+Math.max(0,(s.length-usedL)/2),uy=s.y+Math.max(0,(s.width-usedW)/2),u={x:ux,y:uy,length:usedL,width:usedW,height:usedH};
      // If the last populated layer ends on a complete row, every point of
      // the rectangular used footprint is supported, so it is valid to build
      // another layer above it. An incomplete final row must not create space.
      const fullBlock = rem===0 || rem%cols===0
      spaces=prune([...spaces.filter(x=>x!==s),...split(s,u,fullBlock)]);let made=0;for(let layer=0;layer<usedLayers&&made<take;layer++){const z=s.z+layer*o.height,count=layer<fullLayers?per:rem,rws=layer<fullLayers?rows:usedRows;if(!count)continue;for(let row=0;row<rws&&made<take;row++){const n=Math.min(cols,count-row*cols);for(let col=0;col<n;col++){abort(options.signal);const x=ux+col*o.length,y=uy+row*o.width;if(x<-EPS||y<-EPS||x+o.length>container.length+EPS||y+o.width>container.width+EPS||z<-EPS||z+o.height>H+EPS)continue;result.push(placed(c,seq++,o,x,y,z));made++;done++;progress?.(Math.min(99,Math.round(done/total*100)))}}if((done&31)===0)await yieldBrowser()}remaining-=made;if(!made)break;await yieldBrowser()}}result=center(result,container);progress?.(100);return result}
