import type { Cargo, Container, PlacedCargo } from '../types'
import { dims, overlap, inBounds } from './geometry'
const EPS=.5,STEP=10
type Orientation={length:number;width:number;rotation:0|90};type Unit={cargo:Cargo;index:number};type Point={x:number;y:number}
const snap=(n:number)=>Math.max(0,Math.round(n/STEP)*STEP)
const key=(x:number,y:number)=>`${x}|${y}`
function orientations(c:Cargo):Orientation[]{const a:Orientation={length:c.length,width:c.width,rotation:0};if(!c.rotatable||Math.abs(c.length-c.width)<EPS)return[a];return[a,{length:c.width,width:c.length,rotation:90}]}
export function expandCargo(cargo:Cargo[]):Unit[]{const out:Unit[]=[];for(const c of cargo){const n=Math.max(0,Math.floor(c.quantity));for(let i=0;i<n;i++)out.push({cargo:c,index:i})}return out}
function makePlaced(u:Unit,o:Orientation,x:number,y:number,z:number):PlacedCargo{return{id:`${u.cargo.id}-${u.index+1}`,cargoId:u.cargo.id,cargoType:u.cargo.type,x:snap(x),y:snap(y),z:snap(z),length:u.cargo.length,width:u.cargo.width,height:u.cargo.height,rotation:o.rotation,weight:u.cargo.weight,color:u.cargo.color,placementMode:'automatic',locked:false}}
function rectArea(a:PlacedCargo,b:PlacedCargo){const A=dims(a),B=dims(b);return Math.max(0,Math.min(a.x+A.length,b.x+B.length)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+A.width,b.y+B.width)-Math.max(a.y,b.y))}
function supportCoverage(p:PlacedCargo,supports:PlacedCargo[]){if(p.z<=EPS)return 1;const d=dims(p),area=d.length*d.width;if(!supports.length)return 0;const xs:number[]=[p.x,p.x+d.length],ys:number[]=[p.y,p.y+d.width];for(const q of supports){const qd=dims(q);xs.push(Math.max(p.x,q.x),Math.min(p.x+d.length,q.x+qd.length));ys.push(Math.max(p.y,q.y),Math.min(p.y+d.width,q.y+qd.width))}const xv=[...new Set(xs)].sort((a,b)=>a-b),yv=[...new Set(ys)].sort((a,b)=>a-b);let covered=0;for(let i=0;i<xv.length-1;i++)for(let j=0;j<yv.length-1;j++){const cx=(xv[i]+xv[i+1])/2,cy=(yv[j]+yv[j+1])/2;if(supports.some(q=>{const d=dims(q);return cx>=q.x-EPS&&cx<=q.x+d.length+EPS&&cy>=q.y-EPS&&cy<=q.y+d.width+EPS}))covered+=(xv[i+1]-xv[i])*(yv[j+1]-yv[j])}return Math.min(1,covered/area)}
function supportAllowed(q:PlacedCargo,top:Cargo,defs:Map<string,Cargo>,items:PlacedCargo[]){const d=defs.get(q.cargoId);if(!d||!d.loadBearing||d.breakablePallet)return false;if(d.maxLoadOnTop>0&&top.weight>d.maxLoadOnTop+EPS)return false;if(d.maxStackLayers>0){let layers=1;for(const below of items){if(below.id!==q.id&&Math.abs(below.z+below.height-q.z)<=EPS&&rectArea(q,below)>EPS)layers++}if(layers>=d.maxStackLayers)return false}return true}
function collision(p:PlacedCargo,items:PlacedCargo[]){return items.some(q=>overlap(p,q))}
function xyCandidates(items:PlacedCargo[],c:Container):Point[]{const out:Point[]=[{x:0,y:0}],seen=new Set<string>([key(0,0)]);const add=(x:number,y:number)=>{x=snap(x);y=snap(y);if(x<0||y<0||x>c.length||y>c.width)return;const k=key(x,y);if(!seen.has(k)){seen.add(k);out.push({x,y})}};const xs=[0,...items.flatMap(q=>{const d=dims(q);return[q.x,q.x+d.length]})],ys=[0,...items.flatMap(q=>{const d=dims(q);return[q.y,q.y+d.width]})];for(const x of xs)for(const y of ys)add(x,y);out.sort((a,b)=>a.y-b.y||a.x-b.x);return out}
function highestSupportedZ(x:number,y:number,o:Orientation,cargo:Cargo,items:PlacedCargo[],defs:Map<string,Cargo>){if(!cargo.stackable)return 0;const probe={id:'probe',cargoId:cargo.id,cargoType:cargo.type,x,y,z:0,length:cargo.length,width:cargo.width,height:cargo.height,rotation:o.rotation,weight:cargo.weight,color:cargo.color,placementMode:'automatic',locked:false} as PlacedCargo;let best=0;for(const q of items){if(rectArea(probe,q)<=EPS)continue;const top=q.z+q.height;if(top<=best+EPS)continue;const supports=items.filter(s=>Math.abs(s.z+s.height-top)<=EPS&&rectArea(probe,s)>EPS);const test={...probe,z:top};if(supports.length&&supportCoverage(test,supports)>=.995&&supports.every(s=>supportAllowed(s,cargo,defs,items)))best=top}return best}
function placementScore(p:PlacedCargo,items:PlacedCargo[],c:Container){const d=dims(p),area=d.length*d.width;let contact=0;for(const q of items){const a=rectArea(p,q);if(a>EPS)contact+=a/area}const walls=(p.x<=EPS?1:0)+(p.y<=EPS?1:0)+(Math.abs(p.x+d.length-c.length)<=EPS?1:0)+(Math.abs(p.y+d.width-c.width)<=EPS?1:0);return p.z*1e9+p.y*1e4+p.x*10-contact*600-walls*40}
function orderUnits(cargo:Cargo[]):Unit[]{return expandCargo(cargo).filter(u=>u.cargo.length>0&&u.cargo.width>0&&u.cargo.height>0).sort((a,b)=>{const af=a.cargo.length*a.cargo.width,bf=b.cargo.length*b.cargo.width,av=af*a.cargo.height,bv=bf*b.cargo.height;return bf-af||b.cargo.height-a.cargo.height||bv-av})}
function validLocked(locked:PlacedCargo[],c:Container,quantities:Map<string,number>){const out:PlacedCargo[]=[];for(const p of locked){if((quantities.get(p.cargoId)||0)<=0||!inBounds(p,c))continue;if(out.some(q=>overlap(p,q)))continue;out.push(p)}return out}
function packOne(u:Unit,items:PlacedCargo[],c:Container,defs:Map<string,Cargo>,totalWeight:number){const points=xyCandidates(items,c);let best:PlacedCargo|undefined,bestScore=Infinity;for(const o of orientations(u.cargo)){if(o.length>c.length+EPS||o.width>c.width+EPS||u.cargo.height>c.height+EPS)continue;for(const pt of points){const z=highestSupportedZ(pt.x,pt.y,o,u.cargo,items,defs);if(pt.x+o.length>c.length+EPS||pt.y+o.width>c.width+EPS||z+u.cargo.height>c.height+EPS)continue;const p=makePlaced(u,o,pt.x,pt.y,z);if(totalWeight+p.weight>c.maxPayload+EPS||collision(p,items))continue;if(p.z>EPS){const supports=items.filter(q=>Math.abs(q.z+q.height-p.z)<=EPS&&rectArea(p,q)>EPS);if(supportCoverage(p,supports)<.995||!supports.every(q=>supportAllowed(q,u.cargo,defs,items)))continue}const score=placementScore(p,items,c);if(score<bestScore){bestScore=score;best=p}}}return best}
function packCore(cargo:Cargo[],c:Container,locked:PlacedCargo[],onStep?:(i:number,total:number)=>void){const defs=new Map(cargo.map(x=>[x.id,x])),quantities=new Map(cargo.map(x=>[x.id,Math.floor(x.quantity)]));const items=validLocked(locked,c,quantities),lockedCount=new Map<string,number>();for(const p of items)lockedCount.set(p.cargoId,(lockedCount.get(p.cargoId)||0)+1);const units=orderUnits(cargo).filter(u=>u.index>=(lockedCount.get(u.cargo.id)||0));let totalWeight=items.reduce((s,p)=>s+p.weight,0);for(let i=0;i<units.length;i++){const best=packOne(units[i],items,c,defs,totalWeight);if(best){items.push(best);totalWeight+=best.weight}onStep?.(i+1,units.length)}return items}
export function autoPack(cargo:Cargo[],c:Container,locked:PlacedCargo[]=[]){return packCore(cargo,c,locked)}
export async function autoPackAsync(cargo:Cargo[],c:Container,locked:PlacedCargo[]=[],onProgress?:(percent:number)=>void){const total=expandCargo(cargo).length;if(!total){onProgress?.(100);return validLocked(locked,c,new Map(cargo.map(x=>[x.id,Math.floor(x.quantity)])))}const defs=new Map(cargo.map(x=>[x.id,x])),quantities=new Map(cargo.map(x=>[x.id,Math.floor(x.quantity)]));const items=validLocked(locked,c,quantities),lockedCount=new Map<string,number>();for(const p of items)lockedCount.set(p.cargoId,(lockedCount.get(p.cargoId)||0)+1);const units=orderUnits(cargo).filter(u=>u.index>=(lockedCount.get(u.cargo.id)||0));let totalWeight=items.reduce((s,p)=>s+p.weight,0);for(let i=0;i<units.length;i++){const best=packOne(units[i],items,c,defs,totalWeight);if(best){items.push(best);totalWeight+=best.weight}if(i%4===0)await new Promise<void>(r=>setTimeout(r,0));onProgress?.(Math.round((i+1)/units.length*100))}onProgress?.(100);return items}
