import { Line } from '@react-three/drei'
import { useEffect, useMemo, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import * as THREE from 'three'
import type { Container, SecuringItem } from '../types'
import type { SceneTool } from './ContainerScene'

const S=.001
function Rope({a,b,radius=.002,color='#3d4543'}:{a:THREE.Vector3;b:THREE.Vector3;radius?:number;color?:string}){const mid=useMemo(()=>a.clone().add(b).multiplyScalar(.5),[a,b]);const len=useMemo(()=>a.distanceTo(b),[a,b]);const q=useMemo(()=>new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize()),[a,b]);return <mesh position={mid} quaternion={q} raycast={()=>null}><cylinderGeometry args={[radius,radius,len,8]}/><meshStandardMaterial color={color} roughness={.72}/></mesh>}
export default function SecuringModel({item,container,selected,onSelect,onMove,onRotate,onScale,onDragState,airBagStretch=true,focusMode=false,tool='move'}:{item:SecuringItem;container:Container;selected:boolean;onSelect:()=>void;onMove:(id:string,x:number,y:number)=>void;onRotate:(id:string,rotation:number)=>void;onScale:(id:string,factor:number)=>void;onDragState:(v:boolean)=>void;airBagStretch?:boolean;focusMode?:boolean;tool?:SceneTool}){
 const ref=useRef<THREE.Group>(null),dragRef=useRef(false),startX=useRef(0),startY=useRef(0),lastFactor=useRef(1);const plane=useRef(new THREE.Plane());const [hovered,setHovered]=useState(false)
 const center:[number,number,number]=[(item.x+item.length/2-container.length/2)*S,(item.y+item.width/2-container.width/2)*S,(item.z+item.height/2)*S]
 const begin=(e:any)=>{e.stopPropagation();onSelect();if(tool==='rotate'){onRotate(item.id,(item.rotation+90)%360);return}if(tool==='scale'){dragRef.current=true;onDragState(true);startX.current=e.clientX;startY.current=e.clientY;lastFactor.current=1;return}const z=center[2];plane.current.set(new THREE.Vector3(0,0,1),-z);const pt=e.ray.intersectPlane(plane.current,new THREE.Vector3());if(!pt)return;dragRef.current=true;onDragState(true);(ref.current as any)._offset=[center[0]-pt.x,center[1]-pt.y];(ref.current as any)._last=[item.x,item.y];(e.target as any)?.setPointerCapture?.(e.pointerId)}
 const move=(e:any)=>{if(!dragRef.current)return;e.stopPropagation();if(tool==='scale'){const dy=(e.clientY-startY.current);const f=Math.max(.25,Math.min(4,1-dy*.008));onScale(item.id,f/lastFactor.current);lastFactor.current=f;return}const pt=e.ray.intersectPlane(plane.current,new THREE.Vector3());if(!pt)return;const off=(ref.current as any)._offset||[0,0];const x=Math.round(((pt.x+off[0])/S-item.length/2+container.length/2)/10)*10;const y=Math.round(((pt.y+off[1])/S-item.width/2+container.width/2)/10)*10;if(x>=0&&y>=0&&x+item.length<=container.length&&y+item.width<=container.width){(ref.current as any)._last=[x,y];if(ref.current){ref.current.position.x=(x+item.length/2-container.length/2)*S;ref.current.position.y=(y+item.width/2-container.width/2)*S}}}
 const end=(e:any)=>{if(!dragRef.current)return;e.stopPropagation();dragRef.current=false;onDragState(false);if(tool==='scale'){const dy=(e.clientY-startY.current);const f=Math.max(.25,Math.min(4,1-dy*.008));onScale(item.id,f/lastFactor.current);lastFactor.current=1}else{const last=(ref.current as any)?._last;if(last)onMove(item.id,last[0],last[1])}(e.target as any)?.releasePointerCapture?.(e.pointerId)}
 useEffect(()=>{if(!selected)return;const key=(e:KeyboardEvent)=>{if(e.ctrlKey||e.altKey||e.metaKey)return;if((e.target as HTMLElement)?.tagName==='INPUT')return;if(e.key.toLowerCase()==='r'){e.preventDefault();onRotate(item.id,(item.rotation+90)%360)}if(e.key==='Escape'){e.preventDefault();dragRef.current=false;onDragState(false);onSelect()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[selected,item.id,item.rotation,onRotate,onDragState,onSelect])
 let body:ReactNode
 if(item.type==='triangleWood'){const L=item.length*S,W=item.width*S,H=item.height*S;const shape=new THREE.Shape();shape.moveTo(-L/2,0);shape.lineTo(L/2,0);shape.lineTo(-L/2,H);shape.closePath();body=<mesh position={[0,-W/2,-H/2]} rotation={[Math.PI/2,0,0]} raycast={()=>null}><extrudeGeometry args={[shape,{depth:W,bevelEnabled:false}]}/><meshStandardMaterial color={selected?'#e4a04c':'#9b6738'} roughness={.86}/></mesh>}
 else if(item.type==='airBag'){const L=item.length*S,W=item.width*S,H=item.height*S;const skin=selected?'#f1dda8':'#dcc793';body=<group raycast={()=>null}><mesh scale={[L*.45,W*.30,H*.28]} raycast={()=>null}><sphereGeometry args={[1,14,8]}/><meshStandardMaterial color={skin} roughness={.58}/></mesh><mesh position={[L*.25,0,0]} scale={[L*.28,W*.30,H*.25]} raycast={()=>null}><sphereGeometry args={[1,12,8]}/><meshStandardMaterial color={skin} roughness={.58}/></mesh><mesh position={[-L*.25,0,0]} scale={[L*.28,W*.30,H*.25]} raycast={()=>null}><sphereGeometry args={[1,12,8]}/><meshStandardMaterial color={skin} roughness={.58}/></mesh></group>}
 else if(item.type==='doorNet'){const w=item.width*S,h=item.height*S,cols=14,rows=12,ropes:ReactNode[]=[];for(let i=0;i<=cols;i++){const x=-w/2+i*w/cols;ropes.push(<Rope key={'v'+i} a={new THREE.Vector3(-.025,x,-h/2)} b={new THREE.Vector3(-.025,x,h/2)} radius={.006}/>) }for(let j=0;j<=rows;j++){const z=-h/2+j*h/rows;ropes.push(<Rope key={'h'+j} a={new THREE.Vector3(-.025,-w/2,z)} b={new THREE.Vector3(-.025,w/2,z)} radius={.006}/>) }body=<group>{ropes}</group>}
 else {const pts=item.path&&item.path.length>1?item.path.map(q=>new THREE.Vector3((q.x-container.length/2)*S,(q.y-container.width/2)*S,q.z*S)):[new THREE.Vector3(-1.5,0,.04),new THREE.Vector3(0,0,.5),new THREE.Vector3(1.5,0,.04)];const curve=new THREE.CatmullRomCurve3(pts);body=<mesh geometry={new THREE.TubeGeometry(curve,12,.004,6,false)} raycast={()=>null}><meshStandardMaterial color={selected?'#e56a45':'#b24b35'} roughness={.55}/></mesh>}
 const scale=focusMode?1.35:1
 return <group ref={ref} position={center} scale={[scale,scale,scale]} rotation={[0,0,item.rotation*Math.PI/180]} onPointerOver={e=>{e.stopPropagation();setHovered(true)}} onPointerOut={e=>{e.stopPropagation();setHovered(false)}} onPointerDown={begin} onPointerMove={move} onPointerUp={end} onClick={e=>{e.stopPropagation();onSelect()}}><mesh userData={{collisionBody:false,securingBody:true}}><boxGeometry args={[Math.max(item.length,220)*S,Math.max(item.width,220)*S,Math.max(item.height,120)*S]}/><meshBasicMaterial transparent opacity={selected||hovered?.08:.025} depthWrite={false}/></mesh>{body}</group>
}
