from pathlib import Path
p=Path('src/App.tsx')
s=p.read_text()
# progress cancellation controller
s=s.replace("  const [packingProgress, setPackingProgress] = useState<number | null>(null)\n", "  const [packingProgress, setPackingProgress] = useState<number | null>(null)\n  const packingControllerRef = useRef<AbortController | null>(null)\n")
old_run="""  const runPacking = async (nextContainer = container) => {\n    if (packingProgress !== null) return\n    const locked = placed.filter((p) => p.locked)\n    setPackingProgress(0)\n    setMessage('')\n    let lastProgress = -1\n    try {\n      const result = await autoPackAsync(cargo, nextContainer, locked, (percent) => {\n        const safePercent = Math.min(100, Math.max(0, Math.round(percent)))\n        if (safePercent !== lastProgress) {\n          lastProgress = safePercent\n          setPackingProgress(safePercent)\n        }\n      })\n      setPlaced(result)\n      setSelectedId(null)\n      setSelectedIds([])\n      setMessage(lang === 'zh' ? '自动装柜完成' : 'Auto packing complete')\n    } finally {\n      setPackingProgress(null)\n    }\n  }\n"""
new_run="""  const runPacking = async (nextContainer = container) => {\n    if (packingProgress !== null) return\n    const locked = placed.filter((p) => p.locked)\n    const controller = new AbortController()\n    packingControllerRef.current = controller\n    setPackingProgress(0)\n    setMessage('')\n    let lastProgress = -1\n    try {\n      const result = await autoPackAsync(cargo, nextContainer, locked, (percent) => {\n        const safePercent = Math.min(100, Math.max(0, Math.round(percent)))\n        if (safePercent !== lastProgress) {\n          lastProgress = safePercent\n          setPackingProgress(safePercent)\n        }\n      }, { signal: controller.signal })\n      if (controller.signal.aborted) return\n      setPlaced(result)\n      setSelectedId(null)\n      setSelectedIds([])\n      setMessage(lang === 'zh' ? '自动装柜完成' : 'Auto packing complete')\n    } catch (error) {\n      if (!controller.signal.aborted) {\n        console.error(error)\n        setMessage(lang === 'zh' ? '装柜计算失败，请重试' : 'Packing calculation failed')\n      }\n    } finally {\n      if (packingControllerRef.current === controller) packingControllerRef.current = null\n      setPackingProgress(null)\n    }\n  }\n\n  const cancelPacking = () => {\n    packingControllerRef.current?.abort()\n    setPackingProgress(null)\n    setMessage(lang === 'zh' ? '已取消装柜计算' : 'Packing cancelled')\n  }\n"""
if old_run not in s: raise SystemExit('runPacking block not found')
s=s.replace(old_run,new_run)
# explicit stack limits UI
marker="""                  <div\n                    className={`cargo-volume ${"""
insert="""                  <div className=\"fields stack-limit-fields\">\n                    <label>\n                      {lang === 'zh' ? '最大堆叠层数' : 'Max Stack Layers'}\n                      <input type=\"number\" min=\"0\" value={c.maxStackLayers || 0} onChange={(e) => update(c.id, 'maxStackLayers', Math.max(0, Math.floor(Number(e.target.value) || 0)))} />\n                      <small>{lang === 'zh' ? '0 = 不限制，按集装箱实际内高' : '0 = unlimited; use actual internal height'}</small>\n                    </label>\n                    <label>\n                      {lang === 'zh' ? '最大顶部承重 (kg)' : 'Max Top Load (kg)'}\n                      <input type=\"number\" min=\"0\" value={c.maxLoadOnTop || 0} onChange={(e) => update(c.id, 'maxLoadOnTop', Math.max(0, Number(e.target.value) || 0))} />\n                      <small>{lang === 'zh' ? '0 = 不限制' : '0 = unlimited'}</small>\n                    </label>\n                  </div>\n\n"""+marker
if marker not in s: raise SystemExit('cargo volume marker not found')
s=s.replace(marker,insert,1)
# progress overlay cancel button
old_overlay="""                  <span>{lang === 'zh' ? '正在搜索摆放位置与旋转组合，请稍候…' : 'Searching placement and rotation combinations…'}</span>\n                </div>"""
new_overlay="""                  <span>{lang === 'zh' ? '正在搜索摆放位置与旋转组合，请稍候…' : 'Searching placement and rotation combinations…'}</span>\n                  <button className=\"packing-cancel\" onClick={cancelPacking}>{lang === 'zh' ? '取消计算' : 'Cancel'}</button>\n                </div>"""
if old_overlay not in s: raise SystemExit('progress overlay marker not found')
s=s.replace(old_overlay,new_overlay,1)
# keep export images proportional when compositing
old_draw="""    const a1=await createImageBitmap(new Blob([top],{type:'image/png'})),a2=await createImageBitmap(new Blob([sf],{type:'image/png'}));ctx.drawImage(a1,40,30,1520,420);ctx.drawImage(a2,40,480,1520,440);a1.close();a2.close()"""
new_draw="""    const a1=await createImageBitmap(new Blob([top],{type:'image/png'})),a2=await createImageBitmap(new Blob([sf],{type:'image/png'}));\n    const fit=(bmp:ImageBitmap,x:number,y:number,w:number,h:number)=>{const r=Math.min(w/bmp.width,h/bmp.height);const dw=bmp.width*r,dh=bmp.height*r;ctx.drawImage(bmp,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}\n    fit(a1,40,30,1520,420);fit(a2,40,480,1520,440);a1.close();a2.close()"""
if old_draw not in s: raise SystemExit('export draw marker not found')
s=s.replace(old_draw,new_draw,1)
p.write_text(s)
